
services:
  postgres:
    image: postgres:latest
    container_name: event-manager-db
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EventManager
    ports:
      - "5431:5432"


    #TO FEATURES

#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - main-network


#  zookeeper:
#      image: wurstmeister/zookeeper:3.4.6
#      container_name: zookeeper
#      ports:
#        - "2181:2181"
#      networks:
#        - main_network
#
#  kafka:
#        image: wurstmeister/kafka:2.13-2.8.0
#        container_name: kafka
#        ports:
#          - "9092:9092"
#        environment:
#          KAFKA_BROKER_ID: 1
#          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#        depends_on:
#          - zookeeper
#        networks:
#          - main-network

#volumes:
#  pgdata:
#
#networks:
#  main_network:
